!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  application: AXJ1
  encryptionProtocol: None
  host: CWCC.compuware.com
  hostCodePage: '1047'
  pathMappings:
  - path: **\AMAC
    types:
    - fileExtension: amac
      ispwType: AMAC
  - path: **\ASM
    types:
    - fileExtension: asm
      ispwType: ASM
  - path: **\C
    types:
    - fileExtension: c
      ispwType: C
  - path: **\CLST
    types:
    - fileExtension: clst
      ispwType: CLST
  - path: **\COB
    types:
    - fileExtension: cbl
      ispwType: COB
  - path: **\COPY
    types:
    - fileExtension: cpy
      ispwType: COPY
  - path: **\H
    types:
    - fileExtension: h
      ispwType: H
  - path: **\JOB
    types:
    - fileExtension: jcl
      ispwType: JOB
  - path: **\PLI
    types:
    - fileExtension: pli
      ispwType: PLI
  port: 16196
  readWriteTimeout: 0
  stream: FTSDEMO
