node {
  // this is the groovy script for the Jenkinsfile use in the ISPW GIT
  // INTEGRATION DEMO - there are three steps
  // Perform a checkout of the source code
  // Perform the Git to ISPW synchronization
  // Perform a build
  
    String MF_TSOId_Token         = "CWCC_TSO_LOGIN"    
    String HCI_Token              = "d2e2c4fc-c1af-4097-a1f2-57cb525cd7e" 
     
  stage ('Checkout') 
  {
    // Get the code from the Git repository
    checkout scm
  }

  stage('Git to ISPW Synchronization')
  { 
     gitToIspwIntegration app: 'AXJ1',
     branchMapping: '''*feature* =>QA1,per-branch
     master =>STG,per-branch
     ''', 
     connectionId: "${HCI_Token}",
     credentialsId:"${MF_TSOId_Token}",
     gitCredentialsId: 'JENKINS_GITHUB_USER', 
     gitRepoUrl: 'https://github.com/alanjohnscompuware/ISPWGITAXJ1.git',
     ispwConfigPath: 'ISPW_GIT_demo/ispwconfig.yml', 
     stream: 'FTSDEMO'
  }
  
  stage('Build ISPW assignment')
  // this version automatically pick up the assignment
  {
    ispwOperation    connectionId: "${HCI_Token}", 
    credentialsId: "${MF_TSOId_Token}",
    ispwAction: 'BuildAssignment', 
    ispwRequestBoby:   '''buildautomatically=true'''
  }
}







