node {
  // this is the groovy script for the Jenkinsfile use in the ISPW GIT
  // INTEGRATION DEMO - there are three steps
  // Perform a checkout of the source code
  // Perform the Git to ISPW synchronization
  // Perform a build
  // on CWCC TSO login is 'HUK0320_CWCC_TSO' credentials_ID value
  // on CWCC jenkins logon is '2e557158-9714-4112-bd1c-75d4ff6a14e9' 
  //   connectionid value
  
  // on local TSO login is 'CWCC_TSO_LOGIN' credentials id value
  //on local Jenkins logon is 'LOCAL_CWCC_HCI' connection id value
  
    String MF_TSOId_Token         = "CWCC_TSO_LOGIN"    
    String HCI_Token              = "LOCAL_CWCC_HCI" 

     
  stage ('Checkout') 
  {
    // Get the code from the Git repository
    checkout scm
  }

  stage('Git to ISPW Synchronization')
  { 
     gitToIspwIntegration app: 'AXJ1',
     branchMapping: '''*feature* =>QA1,per-branch
     master =>STG,per-branch
     ''', 
     connectionId: "${HCI_Token}",
     credentialsId:"${MF_TSOId_Token}",
     gitCredentialsId: 'JENKINS_GITHUB_USER', 
     gitRepoUrl: 'https://github.com/alanjohnscompuware/ISPWGITAXJ1.git',
     ispwConfigPath: 'ISPW_GIT_demo/ispwconfig.yml', 
     stream: 'FTSDEMO'
  }
  
  stage('Build ISPW assignment')
  // this version automatically pick up the assignment
  {
    ispwOperation    connectionId: "${HCI_Token}", 
    credentialsId: "${MF_TSOId_Token}",
    ispwAction: 'BuildAssignment', 
    ispwRequestBoby:   '''buildautomatically=true'''
  }
}







